### ISSUE TITLE
Restart the Puppet Master after hiera.yaml Change?

### ISSUE THREAD

**Issue by discreet** [tampakrap/puppet-hiera#2]
It doesn't look like this module restarts the Puppet master after a change to the hiera.yaml file. Was this by design? I believe the Puppet master needs to be restarted for changes to be picked up correct?

**Comment by tampakrap** [comment]
I have already implemented a solution in a branch called restart_puppetmaster. I'm going to merge it to master soon (possibly this weekend), but I'll do a new forge release after we get a new ploperations/puppet release first.

https://github.com/tampakrap/puppet-hiera/tree/restart_puppetmaster

**Comment by tampakrap** [comment]
fixed in 0.2.0
